adding Woltka v0.1.4, pairends + suppress singleton & discordant + rm mux/demux
qiita-spots/qp-woltka pull request #30
Opened 2024-09-03 22:14 UTC by antgonza

… mux/demux

2024-09-09 18:40 UTC, charles-cowart requested changes
Everything appears in order. Just one question.

2024-09-09 18:40 UTC, charles-cowart commented on scripts/woltka_merge
> +# import biom
should these commented imports be removed?

2024-09-10 00:57 UTC, charles-cowart commented
just to clarify, we are consulting with @wasade  on one small point before final approval and merging.

2024-09-11 12:59 UTC, antgonza commented
@charles-cowart, this is ready for final review & merge.

2024-09-12 22:12 UTC, charles-cowart approved these changes

2024-09-12 22:19 UTC, merged